services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILD_REVISION: ${BUILD_REVISION:-$(git rev-parse --short HEAD)}
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      data-access:
        condition: service_healthy
      storage:
        condition: service_healthy

  data-access:
    build:
      context: services/data-access
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILD_REVISION: ${BUILD_REVISION:-$(git rev-parse --short HEAD)}
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  storage:
    build:
      context: services/storage
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        BUILD_REVISION: ${BUILD_REVISION:-$(git rev-parse --short HEAD)}
    ports:
      - "3002:3002"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
