[package]
name = "rust-shared"
version = "0.1.0"
edition = "2021"
description = "Shared Rust types and utilities for ffxiv-tools"
authors = ["Sjur Sutterud Sagen"]

[lib]
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
ts-rs = { version = "10.1.0", features = ["serde-compat"] }
