import { URLS } from "./urls";

export const HEALTH = {
  TIMEOUT_MS: 5000,
  MAX_RETRIES: 2,
  SERVICES: {
    DATA_ACCESS: {
      DEVELOPMENT: `${URLS.ENVIRONMENTS.DEVELOPMENT.DATA_ACCESS}${URLS.SERVICES.DATA_ACCESS.HEALTH}`,
      PRODUCTION: `${URLS.ENVIRONMENTS.PRODUCTION.DATA_ACCESS}${URLS.SERVICES.DATA_ACCESS.HEALTH}`,
    },
    STORAGE: {
      DEVELOPMENT: `${URLS.ENVIRONMENTS.DEVELOPMENT.STORAGE}${URLS.SERVICES.STORAGE.HEALTH}`,
      PRODUCTION: `${URLS.ENVIRONMENTS.PRODUCTION.STORAGE}${URLS.SERVICES.STORAGE.HEALTH}`,
    },
  },
} as const;

export type HealthConfig = typeof HEALTH;
