# Build caching
[build]
rustc-wrapper = "sccache"

# Use faster linker
# For linux/macOS
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# For Windows (lld):
[target.x86_64-pc-windows-msvc]
linker = "lld-link"