[package]
name = "ffxiv-tools-data-access-api"
version = "0.1.0"
edition = "2021"
description = "Data Access API service for ffxiv-tools"
authors = ["Sjur Sutterud Sagen"]

[dependencies]
rust-shared = { workspace = true }
axum = "0.8.1"
polars = "0.45.1"
serde = "1.0.217"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
hyper = { version = "1.5.2", features = ["full"] }
tokio-test = "0.4.4"
tower = "0.5.2"
